spring:
  application:
    name: expensetracker

  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: postgres
    password: nerdyco
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/expense-realm
          jwk-set-uri: http://localhost:8080/realms/expense-realm/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8080
  realm: expense-realm
  client-id: expense-tracker-admin
  client-secret: 9cT1lnx8DjVEvptnw1psWveXimMMXdrb
  admin-username: admin
  admin-password: admin